Args = --no-fallback \
       --install-exit-handlers \
       --enable-preview \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:EnableURLProtocols=http,https,file,jar \
       -H:+JNI \
       -H:+UseServiceLoaderFeature \
       -H:+AllowVMInspection \
       --initialize-at-run-time=com.sun.javafx \
       --initialize-at-run-time=com.sun.glass.ui \
       --initialize-at-run-time=com.sun.prism \
       --initialize-at-run-time=javafx
