Args = --no-fallback \
       --install-exit-handlers \
       --enable-preview \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:EnableURLProtocols=http,https,file,jar \
       -H:+JNI \
       -H:+UseServiceLoaderFeature \
       -H:+AllowVMInspection \
       --initialize-at-build-time=com.sun.javafx.application.PlatformImpl \
       --initialize-at-run-time=com.sun.glass.ui.Application \
       --initialize-at-run-time=javafx.application.Platform \
       --initialize-at-run-time=javafx.scene.media.MediaPlayer \
       --initialize-at-run-time=javafx.scene.text.Font
